from __future__ import annotations

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QDialog, QDialogButtonBox, QLabel, QVBoxLayout

from . import __changelog__, __version__
from .constants import APP_DISPLAY_NAME, APP_NAME, ICON_THEME_NAME


class AboutDialog(QDialog):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle(f"About {APP_DISPLAY_NAME}")
        self.setWindowIcon(QIcon.fromTheme(ICON_THEME_NAME))
        self.setFixedWidth(320)

        layout = QVBoxLayout(self)
        layout.setSpacing(10)

        icon_label = QLabel()
        icon_label.setPixmap(QIcon.fromTheme(ICON_THEME_NAME).pixmap(64, 64))
        icon_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(icon_label)

        title_label = QLabel(
            f"<b>{APP_DISPLAY_NAME} — v{__version__}</b>"
        )
        title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title_label)

        changelog_label = QLabel(
            f"<b>Changelog</b><br>{__changelog__}"
        )
        changelog_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        changelog_label.setWordWrap(True)
        changelog_label.setContentsMargins(10, 8, 10, 8)
        changelog_label.setStyleSheet(
            "background-color: palette(midlight);"
            "border-radius: 6px;"
        )
        layout.addWidget(changelog_label)

        desc_label = QLabel(
            "A lightweight system tray app to monitor your "
            "Claude token usage and rate limits."
            "<br><br>"
            "Fully generated by AI using "
            "<a href='https://claude.ai/claude-code'>Claude Code</a>."
            "<br><br>"
            "<a href='https://github.com/mordup/ctfl'>GitHub</a> · "
            "MIT License"
        )
        desc_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        desc_label.setWordWrap(True)
        desc_label.setOpenExternalLinks(True)
        layout.addWidget(desc_label)

        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok)
        buttons.setCenterButtons(True)
        buttons.accepted.connect(self.accept)
        layout.addWidget(buttons)
